---

name: Gather Pull Request Metadata

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gather-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Store PR number in file
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - name: Upload PR number as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

...
