name: Receive PR

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

jobs:
  get-pr-number:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v3

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
