name: Stable Backport Helper

on:
  schedule:
    # every hour
    - cron: "0 * * * *"

permissions:
  contents: read

jobs:
  stable-backport-helper:
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write

    steps:
      - uses: jamacku/downstream-backport-helper@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
